### ISSUE TITLE
make the opening/ending button disappear after 5 seconds

### ISSUE THREAD

**Issue by Kawsar18** [rebelonion/Dantotsu#150]
can you make the opening/ending button disappear after 5 seconds

**Comment by JohnVictoryz** [comment]
@Kawsar18 i think i will start working on a solution to address this but my schedule is super packed so don't expect it to be done so soon also i am new to kotlin so this might take extra time but i will do my best 🫡

**Comment by sneazy-ibo** [comment]
good luck with exoplayer 🫡

**Comment by JohnVictoryz** [comment]
i sorta made a solution on how it could work based on the code that is already written but i think it should have also a settings option cause many people dont think that it should dissapear but i am stuck on this cause i dont know how to make this a gui option if anyone can help me on the discord server just ping `@tutel` but because of the schedule i dont know if i can manage 

P.S if you would like to help me keep in mind that i am on Europe/Athens time and i will be available at about 9:10 PM to 10:00 PM Europe/Athens time because of some work i have to do other than this also i will try to send this also discord to see if anyone would like to help me there as well

**Comment by JohnVictoryz** [comment]
Made PR with the feature ready :) #224

**Comment by JohnVictoryz** [comment]
This issue can be closed since the pr is now merged
