### ISSUE TITLE
Work with other devs or else progess will stop

### ISSUE THREAD

**Issue by minsoramune** [rebelonion/Dantotsu#387]
We should consider teaming up with developers like @AbandonedCart. They've already added features that users from dantotsu have been asking for. Even though @rebelonion and @AbandonedCart had a falling out, we shouldn't let that stop us from benefiting from @AbandonedCart's work. Our main aim is to make our project better for users, so let's keep our focus on that. By collaborating with different developers, we can make real strides forward.

**Comment by rebelonion** [comment]
Also that sounds very chatgpt generated

**Comment by rebelonion** [comment]
> NGL if I was dev I wouldn't mind the insults and instead thought of keeping the app updated with features 

You seem to forget I work on this for free, as a hobby project, simply because I enjoy it. 

Having me and my helpers constantly ridiculed and insulted makes it not fun.

**Comment by minsoramune** [comment]
> 
> > NGL if I was dev I wouldn't mind the insults and instead thought of keeping the app updated with features 
> 
> You seem to forget I work on this for free, as a hobby project, simply because I enjoy it. 
> 
> Having me and my helpers constantly ridiculed and insulted makes it not fun.
> 

C'mon even he is working for me 
Okay he ridiculed your staff and from now on he won't, now work together please. His fork has many features and loading and other stuff is way faster then dantotsu please I beg you 
Bet you do a poll in your discord server if people want him to come back 
He has more experience and sometimes he might say something that may make u feel bad but understand all he is doing is for the betterment of the app

**Comment by zaidranger** [comment]
> > 
> > > NGL if I was dev I wouldn't mind the insults and instead thought of keeping the app updated with features 
> > 
> > Having me and my helpers constantly ridiculed and insulted makes it not fun.
> > 
> 
> C'mon even he is working for me 
> Okay he ridiculed your staff and from now on he won't, now work together please. His fork has many features and loading and other stuff is way faster then dantotsu please I beg you 
> Bet you do a poll in your discord server if people want him to come back 
> He has more experience and sometimes he might say something that may make u feel bad but understand all he is doing is for the betterment of the app 

Man you are a total piece of sh*, it's so obvious that you are dragging this just to piss him/her off, "NGL if i was a dev" thank god you're not, because you clearly can't respect others decisions and would force them to do stuffs they don't like. Himitsu is a good fork too, don't ruin this with your sh*tty behaviour, people are starting to follow your suit on discord and it's annoying me since Dantotsu is also good on it's own. No devs deserves this kind of treatment.

**Comment by rebelonion** [comment]
> Man you are a total piece of sh*, it's so obvious that you are dragging this just to piss him/her off, "NGL if i was a dev" thank god you're not, because you clearly can't respect others decisions and would force them to do stuffs they don't like.

I didn't force anyone to leave and I am not inherently against working with anyone, but insulting people who you think are not as good as you does make me not want to work with you. I'm not blameless too. I did fight fire with fire. Either way I'm trying to take a stronger stance against toxicity here so let's chill out a bit with insults

**Comment by zaidranger** [comment]
> I didn't force anyone to leave and I am not inherently against working with anyone, but insulting people who you think are not as good as you does make me not want to work with you. I'm not blameless too. I did fight fire with fire. Either way I'm trying to take a stronger stance against toxicity here so let's chill out a bit with insults

Aight, i'm sorry for using harsh words. It seeems like you though i directed those insult on you, which i'm not. It was for @minsoramune . And i do think i'm better then him/her in this case because of the poor choice of words used to intentionally rub you the wrong way. It sucks to see how someone is treated like this because of the decision they make, din't meant to come out as toxic for this, people on discord are starting to use this to start drama between the devs.
